### ISSUE TITLE
请问组件设计是否有UI设计或者设计图？

### ISSUE THREAD

**Issue by tianlu1677** [megalojs/megalo-ui#1]

**Comment by iuiaoin** [comment]
目前是参照taro-ui的风格来开发的，预计下周可以投入使用，接下来会补齐文档以及继续迭代更新ui库，有任何的意见或建议都可以提出来~
![](https://haitao.nos.netease.com/ba47d983-f593-4238-af06-22978652ead5_378_670.png)
![](https://haitao.nos.netease.com/aa696c3a-baa5-440b-903d-8e644577a4a5_380_668.png)

**Comment by tianlu1677** [comment]
谢谢
